version: '3.9'

services:
  esa:
    image: esa:latest
    build:
      context: .
    container_name: esa_container
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_container:5432/esa
    ports:
      - "8080:8080"
    networks:
      - postgres
  postgres:
    container_name: postgres_container
    image: postgres:16.0-bookworm
    environment:
      POSTGRES_DB: "esa"
      POSTGRES_USER: "esa"
      POSTGRES_PASSWORD: "esa"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - esa-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U esa -d esa"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: "esa@esa.com"
      PGADMIN_DEFAULT_PASSWORD: "esa"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - postgres

volumes:
  esa-data:
  pgadmin-data:

networks:
  postgres:
    driver: bridge
